title: "Jason Daniel — Cyber Defense Portfolio"
description: "Hands-on SOC labs, detections, and incident response notes."
url: "https://cscdanielj.github.io"

# Keep it custom; we’ll use our own layout/CSS
theme: null
plugins:
  - jekyll-seo-tag

author: "Jason Daniel"



